eureka:
  instance:
    instance-id: ${spring.application.name}:${instanceId:${random.value}}
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
spring:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:h2:file:~/Code/products-service/data;AUTO_SERVER=true
    username: root
    password: password
    driver-class-name: org.h2.Driver
  application:
    name: products-service
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
server:
  port: 0